import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Menu, X } from 'lucide-react'

const navLinks = [
  { label: 'Products', href: '#products' },
    { label: 'Media', href: '#media' },
      { label: 'Demos/Shop', href: '#demos' },
        { label: 'Careers', href: '#careers' },
        ]

        export default function Navbar() {
          const [scrolled, setScrolled] = useState(false)
            const [mobileOpen, setMobileOpen] = useState(false)

              useEffect(() => {
                  const handleScroll = () => setScrolled(window.scrollY > 20)
                      window.addEventListener('scroll', handleScroll)
                          return () => window.removeEventListener('scroll', handleScroll)
                            }, [])

                              return (
                                  <motion.header
                                        initial={{ y: -80, opacity: 0 }}
                                              animate={{ y: 0, opacity: 1 }}
                                                    transition={{ duration: 0.6, ease: 'easeOut' }}
                                                          className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
                                                                  scrolled ? 'bg-white/95 backdrop-blur-md shadow-sm' : 'bg-white/90 backdrop-blur-sm'
                                                                        }`}
                                                                            >
                                                                                  <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
                                                                                          <a href="/" className="flex items-center">
                                                                                                    <span className="text-[#0D1211] font-black text-xl tracking-tight select-none">
                                                                                                                N<span className="inline-block" style={{ transform: 'scaleX(-1)', display: 'inline-block' }}>A</span>R
                                                                                                                          </span>
                                                                                                                                  </a>

                                                                                                                                          <nav className="hidden md:flex items-center gap-8">
                                                                                                                                                    {navLinks.map((link) => (
                                                                                                                                                                <a key={link.label} href={link.href}
                                                                                                                                                                              className="text-sm font-medium text-gray-500 hover:text-gray-900 transition-colors duration-200">
                                                                                                                                                                                            {link.label}
                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                          </nav>

                                                                                                                                                                                                                                  <div className="hidden md:flex items-center gap-3">
                                                                                                                                                                                                                                            <a href="#contact"
                                                                                                                                                                                                                                                        className="text-xs font-bold text-[#0D1211] px-4 py-2 rounded-lg border border-gray-300 hover:bg-gray-50 transition-all tracking-wider">
                                                                                                                                                                                                                                                                    CONTACT
                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                        <a href="#launch"
                                                                                                                                                                                                                                                                                                    className="text-xs font-bold text-[#0D1211] px-4 py-2 rounded-lg bg-[#81D8D0] hover:bg-[#5BBDB5] transition-all tracking-wider">
                                                                                                                                                                                                                                                                                                                LAUNCH APP
                                                                                                                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                          <button className="md:hidden p-1 text-gray-700" onClick={() => setMobileOpen(!mobileOpen)}>
                                                                                                                                                                                                                                                                                                                                                    {mobileOpen ? <X size={22} /> : <Menu size={22} />}
                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                        <AnimatePresence>
                                                                                                                                                                                                                                                                                                                                                                                {mobileOpen && (
                                                                                                                                                                                                                                                                                                                                                                                          <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}
                                                                                                                                                                                                                                                                                                                                                                                                      exit={{ opacity: 0, height: 0 }} className="md:hidden bg-white border-t border-gray-100 px-6 pb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                  {navLinks.map((link) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                <a key={link.label} href={link.href}
                                                                                                                                                                                                                                                                                                                                                                                                                                                className="block py-3 text-sm font-medium text-gray-600 border-b border-gray-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => setMobileOpen(false)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {link.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex gap-3 mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="#contact" className="flex-1 text-center text-xs font-bold py-2.5 border border-gray-200 rounded-lg tracking-wider">CONTACT</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <a href="#launch" className="flex-1 text-center text-xs font-bold py-2.5 bg-[#81D8D0] rounded-lg tracking-wider">LAUNCH APP</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </AnimatePresence>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </motion.header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }