import { useRef } from 'react'
import { motion, useInView } from 'framer-motion'

const floatingObjects = [
  { emoji: '💎', top: '10%', left: '5%', delay: 0, size: 'lg' },
    { emoji: '🔒', top: '20%', right: '8%', delay: 0.3, size: 'md' },
      { emoji: '⛓️', bottom: '25%', left: '10%', delay: 0.6, size: 'sm' },
        { emoji: '🌐', top: '35%', right: '15%', delay: 0.9, size: 'md' },
          { emoji: '📊', bottom: '20%', right: '5%', delay: 0.5, size: 'sm' },
            { emoji: '🔐', top: '60%', left: '3%', delay: 0.2, size: 'sm' },
            ]

            export default function CTASection() {
              const ref = useRef(null)
                const inView = useInView(ref, { once: true, margin: '-80px' })

                  return (
                      <section
                            ref={ref}
                                  className="relative py-32 px-6 overflow-hidden"
                                        id="cta"
                                              style={{ background: 'linear-gradient(180deg, #1B2120 0%, #0D1211 100%)' }}
                                                  >
                                                        {/* Floating objects */}
                                                              {floatingObjects.map((obj, i) => (
                                                                      <motion.div
                                                                                key={i}
                                                                                          className={`absolute hidden md:flex items-center justify-center animate-${i % 3 === 0 ? 'float' : i % 3 === 1 ? 'float-delay' : 'float-slow'}`}
                                                                                                    style={{
                                                                                                                top: obj.top,
                                                                                                                            left: (obj as any).left,
                                                                                                                                        right: (obj as any).right,
                                                                                                                                                    bottom: obj.bottom,
                                                                                                                                                              }}
                                                                                                                                                                        initial={{ opacity: 0, scale: 0.5 }}
                                                                                                                                                                                  animate={inView ? { opacity: 0.7, scale: 1 } : {}}
                                                                                                                                                                                            transition={{ delay: obj.delay + 0.3, duration: 0.7 }}
                                                                                                                                                                                                    >
                                                                                                                                                                                                              <div className={`rounded-2xl bg-[#1E2625] border border-[#2A3332] flex items-center justify-center shadow-xl ${
                                                                                                                                                                                                                          obj.size === 'lg' ? 'w-20 h-20 text-3xl' : obj.size === 'md' ? 'w-14 h-14 text-2xl' : 'w-10 h-10 text-lg'
                                                                                                                                                                                                                                    }`}>
                                                                                                                                                                                                                                                {obj.emoji}
                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                  </motion.div>
                                                                                                                                                                                                                                                                        ))}

                                                                                                                                                                                                                                                                              {/* Center content */}
                                                                                                                                                                                                                                                                                    <div className="max-w-3xl mx-auto text-center relative z-10">
                                                                                                                                                                                                                                                                                            <motion.h2
                                                                                                                                                                                                                                                                                                      initial={{ opacity: 0, y: 40 }}
                                                                                                                                                                                                                                                                                                                animate={inView ? { opacity: 1, y: 0 } : {}}
                                                                                                                                                                                                                                                                                                                          transition={{ duration: 0.8 }}
                                                                                                                                                                                                                                                                                                                                    className="text-5xl md:text-6xl font-black text-white leading-tight mb-8"
                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                      Let's build
                                                                                                                                                                                                                                                                                                                                                                <br />
                                                                                                                                                                                                                                                                                                                                                                          something permanent
                                                                                                                                                                                                                                                                                                                                                                                  </motion.h2>

                                                                                                                                                                                                                                                                                                                                                                                          <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                    initial={{ opacity: 0, y: 20 }}
                                                                                                                                                                                                                                                                                                                                                                                                              animate={inView ? { opacity: 1, y: 0 } : {}}
                                                                                                                                                                                                                                                                                                                                                                                                                        transition={{ duration: 0.7, delay: 0.2 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                  className="flex items-center justify-center gap-4 flex-wrap"
                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <motion.a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                href="#contact"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="inline-flex items-center gap-2 text-sm font-bold text-[#0D1211] bg-[#81D8D0] px-8 py-4 rounded-xl hover:bg-[#5BBDB5] transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        whileHover={{ scale: 1.04 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    whileTap={{ scale: 0.97 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Get in touch
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </motion.a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <motion.a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          href="#products"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="inline-flex items-center gap-2 text-sm font-bold text-white border border-[#2A3332] px-8 py-4 rounded-xl hover:border-[#81D8D0] hover:text-[#81D8D0] transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  whileHover={{ scale: 1.04 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              whileTap={{ scale: 0.97 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    View products
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </motion.a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Bottom gradient */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="absolute bottom-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-[#81D8D0]/30 to-transparent" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }