import { useRef } from 'react'
import { motion, useInView } from 'framer-motion'

const brands = [
  { name: 'coinpeck', display: 'coinpeck' },
    { name: 'Tokenfi', display: 'Tokenfi' },
      { name: 'ewx', display: 'ewx' },
        { name: 'SOLAR', display: 'SOLAR' },
          { name: 'Bonq', display: 'Bonq' },
            { name: 'ARKEFI', display: 'ARKEFI' },
              { name: 'PROTR', display: 'PROTR' },
                { name: 'enigmatic', display: 'enigmatic' },
                  { name: 'THE KULT', display: 'THE KULT' },
                    { name: 'Healthier', display: 'Healthier' },
                      { name: 'Dexpert', display: 'Dexpert' },
                        { name: 'Stratumn', display: 'Stratumn' },
                          { name: 'solar', display: 'solar' },
                            { name: 'DAO', display: 'DAO' },
                              { name: 'Palladient', display: 'Palladient' },
                                { name: 'Aventus', display: 'Aventus' },
                                  { name: 'bong', display: 'bong' },
                                  ]

                                  export default function Brands() {
                                    const ref = useRef(null)
                                      const inView = useInView(ref, { once: true, margin: '-60px' })

                                        return (
                                            <section ref={ref} className="bg-white py-16 px-6 overflow-hidden border-t border-gray-100" id="brands">
                                                  <div className="max-w-7xl mx-auto">
                                                          {/* Heading */}
                                                                  <motion.div
                                                                            initial={{ opacity: 0, y: 20 }}
                                                                                      animate={inView ? { opacity: 1, y: 0 } : {}}
                                                                                                transition={{ duration: 0.6 }}
                                                                                                          className="text-center mb-10"
                                                                                                                  >
                                                                                                                            <p className="text-[#65696A] text-sm font-medium">
                                                                                                                                        Trusted by <span className="font-bold text-[#0D1211]">leading</span>
                                                                                                                                                    <br className="sm:hidden" />{' '}
                                                                                                                                                                <span className="font-bold text-[#0D1211]">brands</span> across industries
                                                                                                                                                                          </p>
                                                                                                                                                                                  </motion.div>

                                                                                                                                                                                          {/* Marquee logos */}
                                                                                                                                                                                                  <motion.div
                                                                                                                                                                                                            initial={{ opacity: 0 }}
                                                                                                                                                                                                                      animate={inView ? { opacity: 1 } : {}}
                                                                                                                                                                                                                                transition={{ duration: 0.8, delay: 0.2 }}
                                                                                                                                                                                                                                          className="overflow-hidden relative"
                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                            {/* Fade edges */}
                                                                                                                                                                                                                                                                      <div className="absolute left-0 top-0 bottom-0 w-16 bg-gradient-to-r from-white to-transparent z-10 pointer-events-none" />
                                                                                                                                                                                                                                                                                <div className="absolute right-0 top-0 bottom-0 w-16 bg-gradient-to-l from-white to-transparent z-10 pointer-events-none" />

                                                                                                                                                                                                                                                                                          <div className="flex animate-marquee gap-12 items-center" style={{ width: 'max-content' }}>
                                                                                                                                                                                                                                                                                                      {[...brands, ...brands].map((brand, i) => (
                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                    key={i}
                                                                                                                                                                                                                                                                                                                                                    className="flex-shrink-0 text-[#65696A] font-semibold text-sm tracking-wide opacity-60 hover:opacity-100 transition-opacity cursor-default select-none whitespace-nowrap"
                                                                                                                                                                                                                                                                                                                                                                    style={{ minWidth: '80px', textAlign: 'center' }}
                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                  {brand.display}
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </motion.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Product Spotlight label */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        initial={{ opacity: 0, y: 16 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  animate={inView ? { opacity: 1, y: 0 } : {}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            transition={{ duration: 0.6, delay: 0.4 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="text-center mt-14"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-[#0D1211] text-base font-semibold tracking-wide">Product Spotlight</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }