import { useRef } from 'react'
import { motion, useInView } from 'framer-motion'

const pressFeatures = [
  {
      outlet: 'AXIOS',
          category: 'PRODUCT',
              headline: 'Meet Noor Secure: Your. Eyes. Online.',
                  excerpt: 'The Axios Attack: And What it Reveals About the Full Threat Landscape.',
                      logo: 'AX',
                          dark: true,
                            },
                            ]

                            const otherPress = [
                              { category: 'STORIES', headline: 'Meet Noor Secure: Your Eyes, Online', outlet: 'Noor28' },
                                { category: 'EVENTS', headline: 'The New Developers', outlet: 'Noor28' },
                                ]

                                const featuredIn = [
                                  { name: 'Yahoo Finance', abbr: 'Y' },
                                    { name: 'Bloomberg', abbr: 'B' },
                                      { name: 'TechCrunch', abbr: 'TC' },
                                      ]

                                      export default function MediaSection() {
                                        const ref = useRef(null)
                                          const inView = useInView(ref, { once: true, margin: '-80px' })

                                            return (
                                                <section
                                                      ref={ref}
                                                            className="py-24 px-6 overflow-hidden"
                                                                  id="media"
                                                                        style={{ background: '#0D1211' }}
                                                                            >
                                                                                  <div className="max-w-7xl mx-auto">
                                                                                          {/* Heading */}
                                                                                                  <motion.h2
                                                                                                            initial={{ opacity: 0, y: 30 }}
                                                                                                                      animate={inView ? { opacity: 1, y: 0 } : {}}
                                                                                                                                transition={{ duration: 0.7 }}
                                                                                                                                          className="text-4xl md:text-5xl font-black text-white mb-16"
                                                                                                                                                  >
                                                                                                                                                            Noor28{' '}
                                                                                                                                                                      <span className="italic font-light text-[#8E9492]">in the media</span>
                                                                                                                                                                              </motion.h2>

                                                                                                                                                                                      <div className="grid md:grid-cols-2 gap-8 items-start">
                                                                                                                                                                                                {/* Left: Main feature - AXIOS */}
                                                                                                                                                                                                          <motion.div
                                                                                                                                                                                                                      initial={{ opacity: 0, x: -30 }}
                                                                                                                                                                                                                                  animate={inView ? { opacity: 1, x: 0 } : {}}
                                                                                                                                                                                                                                              transition={{ duration: 0.7, delay: 0.1 }}
                                                                                                                                                                                                                                                          className="product-card rounded-2xl overflow-hidden cursor-pointer"
                                                                                                                                                                                                                                                                      style={{ background: '#111918', border: '1px solid #2A3332' }}
                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                            {/* Dark header */}
                                                                                                                                                                                                                                                                                                        <div className="h-48 flex items-center justify-center relative overflow-hidden"
                                                                                                                                                                                                                                                                                                                      style={{ background: 'linear-gradient(135deg, #161B1A 0%, #0D1211 100%)' }}>
                                                                                                                                                                                                                                                                                                                                    <span className="text-white text-5xl font-black tracking-tighter opacity-80">AXIOS</span>
                                                                                                                                                                                                                                                                                                                                                  <div className="absolute top-3 left-4">
                                                                                                                                                                                                                                                                                                                                                                  <span className="text-[10px] text-[#81D8D0] font-bold uppercase tracking-widest bg-[#81D8D0]/10 px-2 py-1 rounded">
                                                                                                                                                                                                                                                                                                                                                                                    AX STORIES
                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Card body */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="p-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-[#8E9492] text-xs font-bold uppercase tracking-widest mb-2">NOOR ARTICLE</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="text-white text-sm font-semibold leading-snug">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  The Axios Attack: And What it Reveals About the Full Threat Landscape.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <motion.button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              whileHover={{ x: 4 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="mt-3 text-[#81D8D0] text-xs font-semibold flex items-center gap-1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Read more →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </motion.button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </motion.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Right: Column of items */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                initial={{ opacity: 0, x: 30 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            animate={inView ? { opacity: 1, x: 0 } : {}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        transition={{ duration: 0.7, delay: 0.2 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="flex flex-col gap-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Other press items */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { cat: 'PRODUCT', title: 'Meet Noor Secure: Your Eyes, Online', tag: 'New' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  { cat: 'STORIES', title: 'The New Developers', tag: null },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ].map((item, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={i}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="product-card rounded-xl p-4 cursor-pointer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ background: '#111918', border: '1px solid #2A3332' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            whileHover={{ borderColor: '#81D8D0' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-start justify-between gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-[#8E9492] text-[10px] font-bold uppercase tracking-widest mb-1.5">{item.cat}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-white text-sm font-medium leading-snug">{item.title}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {item.tag && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="flex-shrink-0 text-[10px] font-bold text-[#81D8D0] bg-[#81D8D0]/10 px-2 py-0.5 rounded">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {item.tag}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Featured in */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-[#65696A] text-xs uppercase tracking-widest mb-3 font-semibold">Featured in</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex items-center gap-4 flex-wrap">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {['Yahoo Finance', 'Bloomberg', 'Decrypt', 'CoinDesk'].map((outlet) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span key={outlet} className="text-[#8E9492] text-xs font-semibold hover:text-white transition-colors cursor-default">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {outlet}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }