import { useRef } from 'react'
import { motion, useInView } from 'framer-motion'

const socialLinks = [
  {
      platform: 'X (Twitter)',
          handle: '@Noor28',
              description: 'First To Know. First To Move.',
                  icon: 'X',
                      href: 'https://twitter.com/noor28',
                        },
                          {
                              platform: 'LinkedIn',
                                  handle: 'Noor28',
                                      description: 'Inside Access. Real Opportunities.',
                                          icon: 'in',
                                              href: 'https://linkedin.com/company/noor28',
                                                },
                                                  {
                                                      platform: 'Discord',
                                                          handle: 'Noor28',
                                                              description: 'Where The Builders Are.',
                                                                  icon: '◈',
                                                                      href: 'https://discord.gg/noor28',
                                                                        },
                                                                          {
                                                                              platform: 'Telegram',
                                                                                  handle: 'Noor28',
                                                                                      description: 'The Heart. The Operations.',
                                                                                          icon: '✈',
                                                                                              href: 'https://t.me/noor28',
                                                                                                },
                                                                                                ]

                                                                                                export default function TeamSection() {
                                                                                                  const ref = useRef(null)
                                                                                                    const inView = useInView(ref, { once: true, margin: '-80px' })

                                                                                                      return (
                                                                                                          <section
                                                                                                                ref={ref}
                                                                                                                      className="py-24 px-6"
                                                                                                                            id="team"
                                                                                                                                  style={{ background: '#0D1211' }}
                                                                                                                                      >
                                                                                                                                            <div className="max-w-7xl mx-auto">
                                                                                                                                                    <div className="grid md:grid-cols-2 gap-16 items-start">
                                                                                                                                                              {/* Left: Heading + counter */}
                                                                                                                                                                        <motion.div
                                                                                                                                                                                    initial={{ opacity: 0, y: 30 }}
                                                                                                                                                                                                animate={inView ? { opacity: 1, y: 0 } : {}}
                                                                                                                                                                                                            transition={{ duration: 0.7 }}
                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                  <h2 className="text-4xl md:text-5xl font-black text-white leading-tight mb-8">
                                                                                                                                                                                                                                                Build by the{' '}
                                                                                                                                                                                                                                                              <span className="italic font-light">people</span>
                                                                                                                                                                                                                                                                            <br />
                                                                                                                                                                                                                                                                                          who have been there.
                                                                                                                                                                                                                                                                                                      </h2>
                                                                                                                                                                                                                                                                                                                  <p className="text-[#8E9492] leading-relaxed mb-10 max-w-md">
                                                                                                                                                                                                                                                                                                                                Noor28 has over 30 industry professionals. Our team brings together battle-tested operators
                                                                                                                                                                                                                                                                                                                                              from the world's top institutions — crypto natives, quant traders, engineers, and founders
                                                                                                                                                                                                                                                                                                                                                            who have built and scaled real products.
                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                    <motion.a
                                                                                                                                                                                                                                                                                                                                                                                                  href="#careers"
                                                                                                                                                                                                                                                                                                                                                                                                                className="inline-flex items-center gap-2 text-sm font-semibold bg-[#81D8D0] text-[#0D1211] px-6 py-3 rounded-xl hover:bg-[#5BBDB5] transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                              whileHover={{ scale: 1.03 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                            whileTap={{ scale: 0.97 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      View open positions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </motion.a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Right: Social links grid */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            initial={{ opacity: 0, x: 30 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        animate={inView ? { opacity: 1, x: 0 } : {}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transition={{ duration: 0.7, delay: 0.15 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="grid grid-cols-2 gap-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {socialLinks.map((social, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <motion.a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={social.platform}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    href={social.href}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    initial={{ opacity: 0, y: 20 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    animate={inView ? { opacity: 1, y: 0 } : {}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transition={{ delay: 0.2 + i * 0.08, duration: 0.5 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="product-card rounded-2xl p-5 flex flex-col gap-3 group"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ background: '#111918', border: '1px solid #2A3332' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    whileHover={{ borderColor: '#81D8D0', scale: 1.02 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Icon */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="w-10 h-10 rounded-xl bg-[#1E2625] flex items-center justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-white font-bold text-sm group-hover:text-[#81D8D0] transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {social.icon}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Text */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-white text-xs font-bold mb-1">{social.platform}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-[#65696A] text-xs leading-tight">{social.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }